version: '3'

services:
  server:
    image: klakegg/hugo:0.78.2-ext
    command: server
    volumes:
      - "./app:/src"
    ports:
      - "1313:1313"
  build:
    image: klakegg/hugo:0.78.2-ext
    volumes:
      - "./app:/src"
  update:
    image: alpine
    volumes:
      - "./app:/src"
      - "./repos:/repos"
      - "./scripts:/scripts"
    entrypoint: "/scripts/update.sh"